/**
 * AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by scripts/build-content.mjs from the JSON files under content/
 * (including content/properties/).
 * Run `pnpm build:content` to regenerate after editing content/.
 * Any manual edits here will be overwritten.
 */

export interface GeneratedBilingualText {
  en: string;
  es: string;
}

export type GeneratedAccommodationType =
  | 'entire_home'
  | 'apartment'
  | 'private_room'
  | 'shared_room'
  | 'condo';

export type GeneratedExternalPlatform = 'airbnb' | 'booking' | 'vrbo' | 'other';

export interface GeneratedProperty {
  id: string;
  name: GeneratedBilingualText;
  description: GeneratedBilingualText;
  accommodationType: GeneratedAccommodationType;
  location: GeneratedBilingualText;
  monthlyPrice: string;
  priceNotes?: GeneratedBilingualText;
  images: string[];
  externalUrl: string;
  externalPlatform: GeneratedExternalPlatform;
  features?: {
    bedrooms?: number;
    beds?: number;
    bathrooms?: number;
    guests?: number;
  };
  rating?: number;
  reviewCount?: number;
}

export interface GeneratedSettings {
  phone: string;
  phoneLabel: string;
  phoneHref: string;
  email: string;
  instagramHandle: string;
  instagramUrl: string;
  calendlyUrl: string;
  location: GeneratedBilingualText;
}

export interface GeneratedServiceItem {
  title: GeneratedBilingualText;
  description: GeneratedBilingualText;
}

export interface GeneratedPlanItem {
  name: GeneratedBilingualText;
  description: GeneratedBilingualText;
  services: GeneratedBilingualText[];
  cta: GeneratedBilingualText;
}

export interface GeneratedTeamMember {
  id: string;
  name: GeneratedBilingualText;
  role: GeneratedBilingualText;
  greeting: GeneratedBilingualText;
  bio: GeneratedBilingualText;
  photo: string;
  alt: GeneratedBilingualText;
}

export const properties: GeneratedProperty[] = [
  {
    "id": "casa-mafuaye",
    "name": {
      "en": "Casa Mafuáye",
      "es": "Casa Mafuáye"
    },
    "description": {
      "en": "An oasis of tranquility! This beautiful casa is equipped with everything needed for an unforgettable experience. Situated in nature, away from main road noise, and just minutes from the area's primary beaches. Enjoy 200 MB high-speed WiFi and a fully equipped kitchen in this peaceful retreat.",
      "es": "Un oasis de tranquilidad! Esta hermosa casa está equipada con todo lo necesario para una experiencia inolvidable. Situada en la naturaleza, alejada del ruido de la carretera principal, y a solo minutos de las principales playas de la zona. Disfruta de WiFi de alta velocidad de 200 MB y una cocina totalmente equipada en este refugio tranquilo."
    },
    "accommodationType": "entire_home",
    "location": {
      "en": "Nosara, Guanacaste",
      "es": "Nosara, Guanacaste"
    },
    "monthlyPrice": "$2,300",
    "priceNotes": {
      "en": "+ electricity",
      "es": "+ electricidad"
    },
    "images": [
      "/images/properties/casa-mafuaye-piscina.webp",
      "/images/properties/casa-mafuaye-1.webp",
      "/images/properties/casa-mafuaye-2.webp",
      "/images/properties/casa-mafuaye-3.webp",
      "/images/properties/casa-mafuaye-4.webp",
      "/images/properties/casa-mafuaye-5.webp",
      "/images/properties/casa-mafuaye-6.webp",
      "/images/properties/casa-mafuaye-7.webp",
      "/images/properties/casa-mafuaye-8.webp"
    ],
    "externalUrl": "https://www.airbnb.es/rooms/778490681170620001",
    "externalPlatform": "airbnb",
    "features": {
      "guests": 6,
      "bedrooms": 3,
      "beds": 3,
      "bathrooms": 2
    },
    "rating": 4.96,
    "reviewCount": 25
  },
  {
    "id": "become-nosara-luxury",
    "name": {
      "en": "Luxury Condo at Become Nosara",
      "es": "Condominio de Lujo en Become Nosara"
    },
    "description": {
      "en": "Modern 2-bedroom luxury condo in an exclusive community spanning 13,600m². Features spacious open-concept design with high ceilings, elegant stone countertops, rainfall showers, and private outdoor spaces. Enjoy resort-style amenities including pool, yoga spaces, fitness zones, and 24/7 security in a gated community.",
      "es": "Moderno condominio de lujo de 2 habitaciones en una comunidad exclusiva de 13,600m². Cuenta con diseño abierto y espacioso con techos altos, elegantes encimeras de piedra, duchas de lluvia y espacios exteriores privados. Disfruta de amenidades tipo resort incluyendo piscina, espacios de yoga, zonas de fitness y seguridad 24/7 en una comunidad cerrada."
    },
    "accommodationType": "condo",
    "location": {
      "en": "La Esperanza, Nosara, Guanacaste",
      "es": "La Esperanza, Nosara, Guanacaste"
    },
    "monthlyPrice": "$3,000",
    "images": [
      "/images/properties/become-nosara-1.webp"
    ],
    "externalUrl": "https://bluewaterpropertiesofcostarica.com/costa-rica-real-estate/property/luxury-condos-become-nosara/",
    "externalPlatform": "other",
    "features": {
      "bedrooms": 2,
      "bathrooms": 2
    }
  },
  {
    "id": "playa-pelada-home",
    "name": {
      "en": "3 Bedroom Home in Playa Pelada",
      "es": "Casa de 3 Habitaciones en Playa Pelada"
    },
    "description": {
      "en": "A spacious, comfortable residence in the tranquil area of Playa Pelada, just three minutes from the beach. Surrounded by nature with jungle pathways connecting to both Pelada and Guiones beaches. Enjoy privacy and peaceful ambiance while staying close to supermarkets and restaurants.",
      "es": "Una residencia espaciosa y cómoda en la tranquila zona de Playa Pelada, a solo tres minutos de la playa. Rodeada de naturaleza con senderos de selva que conectan con las playas Pelada y Guiones. Disfruta de privacidad y un ambiente tranquilo mientras te mantienes cerca de supermercados y restaurantes."
    },
    "accommodationType": "entire_home",
    "location": {
      "en": "Playa Pelada, Nosara, Guanacaste",
      "es": "Playa Pelada, Nosara, Guanacaste"
    },
    "monthlyPrice": "$2,800",
    "images": [
      "/images/properties/playa-pelada-1.webp"
    ],
    "externalUrl": "https://www.airbnb.com/l/dCIJ3UkR",
    "externalPlatform": "airbnb",
    "features": {
      "bedrooms": 3,
      "guests": 5
    },
    "rating": 4.62,
    "reviewCount": 13
  }
];

export const settings: GeneratedSettings = {
  "phone": "+506 8308 3634",
  "phoneLabel": "Vanessa",
  "phoneHref": "tel:+50683083634",
  "email": "info@hostmatecostarica.com",
  "instagramHandle": "@hostmatecostarica",
  "instagramUrl": "https://instagram.com/hostmatecostarica",
  "calendlyUrl": "https://calendly.com/hostmatecostarica-info/30min",
  "location": {
    "en": "Costa Rica",
    "es": "Costa Rica"
  }
};

export const services: GeneratedServiceItem[] = [
  {
    "title": {
      "en": "Property Listing",
      "es": "Publicación de la Propiedad"
    },
    "description": {
      "en": "Your property will be listed on the right platforms to get the most bookings.",
      "es": "Tu alojamiento estará publicado en las aplicaciones adecuadas para obtener la mayor cantidad de reservas."
    }
  },
  {
    "title": {
      "en": "Calendar Management",
      "es": "Administración de Calendarios"
    },
    "description": {
      "en": "Your property calendar will always be updated and synchronized.",
      "es": "El calendario de tu alojamiento estará siempre actualizado y sincronizado."
    }
  },
  {
    "title": {
      "en": "Decoration Consulting",
      "es": "Asesoría de Decoración"
    },
    "description": {
      "en": "We visit your property and provide a personalized assessment to improve decoration and basic elements.",
      "es": "Vamos a tu alojamiento y hacemos un diagnóstico personalizado para mejorar la decoración y elementos básicos."
    }
  },
  {
    "title": {
      "en": "Property Marketing",
      "es": "Publicidad del Alojamiento"
    },
    "description": {
      "en": "Your property will receive additional advertising on social media and our website for greater visibility.",
      "es": "Tu alojamiento recibirá publicidad adicional en redes sociales y en nuestra página web para mayor visibilidad."
    }
  },
  {
    "title": {
      "en": "Guest Communication",
      "es": "Comunicación con Huéspedes"
    },
    "description": {
      "en": "Daily response to guest inquiries through the platform.",
      "es": "Respuesta de consultas de huéspedes diariamente por medio de la plataforma."
    }
  },
  {
    "title": {
      "en": "Market Research",
      "es": "Estudio de Mercado"
    },
    "description": {
      "en": "Market review by area to determine the best possible price for your property.",
      "es": "Revisión del mercado según la zona para definir el mejor precio posible del alojamiento."
    }
  },
  {
    "title": {
      "en": "Professional Photography",
      "es": "Fotografías Profesionales"
    },
    "description": {
      "en": "Professional photos of your property for better presentation and marketing.",
      "es": "Fotografías profesionales del alojamiento para una mejor presentación y publicidad."
    }
  },
  {
    "title": {
      "en": "Housekeeping",
      "es": "Housekeeping"
    },
    "description": {
      "en": "Cleaning staff with high quality standards and customer service.",
      "es": "Personal de limpieza con altos estándares de calidad y servicio al cliente."
    }
  }
];

export const plans: GeneratedPlanItem[] = [
  {
    "name": {
      "en": "HOSTMATE VIRTUAL",
      "es": "HOSTMATE VIRTUAL"
    },
    "description": {
      "en": "Complete digital management",
      "es": "Gestión digital completa"
    },
    "services": [
      {
        "en": "Property listing",
        "es": "Publicación de la propiedad"
      },
      {
        "en": "Guest communication",
        "es": "Comunicación con los huéspedes"
      },
      {
        "en": "Market research and price updates",
        "es": "Estudio de mercado y actualización de precios"
      },
      {
        "en": "Calendar management",
        "es": "Administración de calendarios"
      },
      {
        "en": "Property marketing",
        "es": "Publicidad del alojamiento"
      },
      {
        "en": "Review management",
        "es": "Gestión de reviews"
      },
      {
        "en": "Monthly booking reports",
        "es": "Reportes de reservas mensuales"
      }
    ],
    "cta": {
      "en": "Choose Virtual",
      "es": "Elegir Virtual"
    }
  },
  {
    "name": {
      "en": "HOSTMATE HYBRID",
      "es": "HOSTMATE HÍBRIDO"
    },
    "description": {
      "en": "Complete service - Digital + On-site",
      "es": "Servicio completo - Digital + Presencial"
    },
    "services": [
      {
        "en": "Property listing",
        "es": "Publicación de la propiedad"
      },
      {
        "en": "Guest communication",
        "es": "Comunicación con los huéspedes"
      },
      {
        "en": "Market research and price updates",
        "es": "Estudio de mercado y actualización de precios"
      },
      {
        "en": "Calendar management",
        "es": "Administración de calendarios"
      },
      {
        "en": "Property marketing",
        "es": "Publicidad del alojamiento"
      },
      {
        "en": "Review management",
        "es": "Gestión de reviews"
      },
      {
        "en": "Monthly booking reports",
        "es": "Reportes de reservas mensuales"
      },
      {
        "en": "Decoration consulting",
        "es": "Asesoría de decoración"
      },
      {
        "en": "Professional photography",
        "es": "Fotografías profesionales"
      },
      {
        "en": "Housekeeping",
        "es": "Housekeeping"
      },
      {
        "en": "Welcome Kit",
        "es": "Welcome Kit"
      }
    ],
    "cta": {
      "en": "Choose Hybrid",
      "es": "Elegir Híbrido"
    }
  },
  {
    "name": {
      "en": "HOSTMATE CUSTOM",
      "es": "HOSTMATE PERSONALIZADO"
    },
    "description": {
      "en": "Tailored to your needs",
      "es": "Plan a tu medida"
    },
    "services": [
      {
        "en": "Book a free 1:1 session",
        "es": "Agenda una sesión 1:1 gratuita"
      },
      {
        "en": "We define your specific needs",
        "es": "Definimos tus necesidades específicas"
      },
      {
        "en": "We create a personalized plan",
        "es": "Creamos un plan personalizado"
      },
      {
        "en": "Total flexibility in services",
        "es": "Flexibilidad total en servicios"
      }
    ],
    "cta": {
      "en": "Book Session",
      "es": "Agendar Sesión"
    }
  }
];

export const team: GeneratedTeamMember[] = [
  {
    "id": "vanessa",
    "name": {
      "en": "Vanessa",
      "es": "Vanessa"
    },
    "role": {
      "en": "Co-founder",
      "es": "Cofundadora"
    },
    "greeting": {
      "en": "Hello, my name is Vanessa.",
      "es": "Hola, mi nombre es Vanessa."
    },
    "bio": {
      "en": "Based in Costa Rica, with a strong connection to Guanacaste, I am inspired by the region's lifestyle and culture.\n\nMy professional background includes systems configuration, finance, and customer experience. I personally manage your listings to ensure operational efficiency, high quality, and profit improvement.\n\nFor me, every property is more than an asset—it is an opportunity to blend strategy, creativity, and genuine hospitality into meaningful guest experiences, creating value and purpose for you, your guests, and Hostmate.",
      "es": "Resido en Costa Rica, con una fuerte conexión con Guanacaste, me inspira el estilo de vida y la cultura de la región.\n\nMi experiencia profesional incluye configuración de sistemas, finanzas y experiencia del cliente. Gestiono personalmente sus listados para garantizar eficiencia operativa, alta calidad y mejora de rentabilidad.\n\nPara mí, cada propiedad es más que un activo—es una oportunidad de combinar estrategia, creatividad y hospitalidad genuina en experiencias significativas para los huéspedes, creando valor y propósito para usted, sus huéspedes y Hostmate."
    },
    "photo": "/assets/Vanessa.webp",
    "alt": {
      "en": "Vanessa - Co-founder of Hostmate Costa Rica",
      "es": "Vanessa - Cofundadora de Hostmate Costa Rica"
    }
  },
  {
    "id": "julian",
    "name": {
      "en": "Julian",
      "es": "Julián"
    },
    "role": {
      "en": "Co-founder",
      "es": "Cofundador"
    },
    "greeting": {
      "en": "Hi, I'm Julian.",
      "es": "Hola, soy Julián."
    },
    "bio": {
      "en": "I manage homes the way I'd expect mine to be managed.\n\nI was raised in Nosara and have built my professional career here. That means I don't just know the area; I understand how it works, who to call, and how things get done on the ground.\n\nAt the same time, my background in marketing and sales has connected me with high-level networks locally and internationally. Hostmate sits at that intersection: local presence with global-level standards.",
      "es": "Gestiono hogares de la manera en que esperaría que gestionaran el mío.\n\nCrecí en Nosara y he construido mi carrera profesional aquí. Eso significa que no solo conozco la zona; entiendo cómo funciona, a quién llamar y cómo se hacen las cosas en el terreno.\n\nAl mismo tiempo, mi experiencia en marketing y ventas me ha conectado con redes de alto nivel local e internacionalmente. Hostmate se encuentra en esa intersección: presencia local con estándares de nivel global."
    },
    "photo": "/assets/Julian.webp",
    "alt": {
      "en": "Julian - Co-founder of Hostmate Costa Rica",
      "es": "Julián - Cofundador de Hostmate Costa Rica"
    }
  }
];
